Repository KUIT-CoNet/CoNet-iOS, pull requests merged in 2024-04, with the labels that each got.

#120 [PR]마이페이지>이름 변경 페이지 버그 해결
  CoNet/Main/MyPage/UserInfo/ChangeNameViewController.swift
  CoNet/Main/MyPage/UserInfo/UserInfoViewController.swift
Labels: 🐶 가은, ✨ feat, 🐛 bug

#121 [PR] 구성원 추가/삭제 기능 추가
  CoNet/API/PlanAPI.swift
  CoNet/DTO/Plan.swift
  CoNet/Main/Cells/Member/EditMemberCollectionViewCell.swift
  CoNet/Main/Cells/Member/SelectMemberCollectionViewCell.swift
  CoNet/Main/Meeting/MeetingTable/MeetingViewController.swift
  CoNet/Main/Plan/PlanDetail/PlanDateButtonSheetViewController.swift
  CoNet/Main/Plan/PlanDetail/PlanInfoEditViewController.swift
  CoNet/Main/Plan/PlanDetail/Sheet/PlanMemberBottonSheetViewController.swift
Labels: 🐱 아현, ✨ feat

#126 [PR] 시간 공유 페이지의 인원 수 별 색 예시 부분 리팩토링
  CoNet.xcodeproj/project.pbxproj
  CoNet/Main/Plan/TimeManage/TimeColorExView.swift
  CoNet/Main/Plan/TimeManage/TimeInputViewController.swift
  CoNet/Main/Plan/TimeManage/TimeShareViewController.swift
Labels: 🐶 가은, 🛠️ refactor
