Repository KUIT-CoNet/CoNet-iOS, pull requests merged in 2024-05, with the labels that each got.

#132 [PR] 구성원 삭제/상세페이지로 수정사항 바로 반영 버그 해결
  CoNet/Main/Cells/Member/EditMemberCollectionViewCell.swift
  CoNet/Main/Plan/PlanDetail/InfoVC/DecidedPlanInfoViewController.swift
  CoNet/Main/Plan/PlanDetail/PlanInfoEditViewController.swift
Labels: 🐱 아현, 🐛 bug

#135 [PR] 자동로그인
  CoNet/Main/Auth/Login/LoginViewController.swift
  CoNet/SceneDelegate.swift
Labels: 🐶 가은, ✨ feat

#133 bug(meetingcode): qa - 텍스트라벨 제약조건 변경
  CoNet/Main/Meeting/MeetingTable/MeetingCodeViewController.swift
Labels: 🐱 아현, 🐛 bug

#136 [PR] QA-I-6 완료
  CoNet/Main/Cells/PlanList/DecidedPlanCell.swift
  CoNet/Main/Meeting/SideBar/SideBarList.swift
  CoNet/Main/Meeting/SideBar/SideBarViewController.swift
  CoNet/Main/Plan/PlanList/DecidedPlan/DecidedPlanListViewController.swift
Labels: 🐶 가은

#137 [PR] QA-I-4,5 완료
  CoNet/Assets.xcassets/icon/clearBtn.imageset/Contents.json
  CoNet/Assets.xcassets/icon/clearBtn.imageset/clearBtn.png
  CoNet/Main/Plan/PlanManage/MakePlanViewController.swift
  CoNet/Main/Plan/TimeManage/TimeShareViewController.swift
Labels: 🐶 가은

#138 [PR] QA-I-8 완료
  CoNet/Main/Plan/TimeManage/TimeInputViewController.swift
  CoNet/Main/Plan/TimeManage/TimeShareViewController.swift
Labels: 🐶 가은

#139 QA-I-16: 캘린더 높이 조절 해결
  CoNet/Main/Plan/PlanDetail/PlanDateButtonSheetViewController.swift
Labels: 🐱 아현, 🐛 bug
