Repository KUIT-CoNet/CoNet-iOS, pull requests merged in 2024-01, with the labels that each got.

#20 [PR] 약속 리스트 리팩토링
  CoNet.xcodeproj/project.pbxproj
  CoNet/Main/Components/PlanList/PlanDummyData.swift
  CoNet/Main/Meeting/PlanList/DecidedPlan/DecidedPlanCell.swift
  CoNet/Main/Meeting/PlanList/DecidedPlan/DecidedPlanListViewController.swift
  CoNet/Main/Meeting/PlanList/WaitingPlan/WaitingPlanCell.swift
  CoNet/Main/Meeting/PlanList/WaitingPlan/WaitingPlanListViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#27 [PR] 문의하기용 이메일 계정 변경
  CoNet/Main/MyPage/InquireViewController.swift
Labels: 🐥 안진

#25 [PR] 모임 메인 - 정보 수정 화면 리팩토링
  CoNet/Main/Meeting/MeetingInfoEditViewController.swift
Labels: 🐱 아현, 🛠️ refactor

#29 [PR] 약속 - 약속 만들기 리팩토링
  CoNet/Main/Meeting/Plan/MakePlanViewController.swift
  CoNet/Main/Meeting/Plan/TimeShareViewController.swift
Labels: 🐱 아현, 🛠️ refactor

#28 [PR] 약속 만들기 API, 특정 날짜 약속 조회 API 버그 수정
  CoNet/Main/Home/CalendarDateFormatter.swift
  CoNet/Main/Home/CalendarViewController.swift
  CoNet/Main/Home/HomeViewController.swift
Labels: 🐶 가은, 🐛 bug, 🛠️ refactor

#32 [PR] 마이페이지 메인 화면, 회원 정보 래픽토링
  CoNet.xcodeproj/project.pbxproj
  CoNet/Main/MyPage/MyPageViewController.swift
  CoNet/Main/MyPage/UserInfo/ChangeNameViewController.swift
  CoNet/Main/MyPage/UserInfo/UserInfoViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#37 [PR] 마이페이지 > 이름 변경 화면 리팩토링
  CoNet.xcodeproj/project.pbxproj
  CoNet/Main/Components/TextField/TextFieldHelperMessage.swift
  CoNet/Main/MyPage/UserInfo/ChangeNameViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#30 [PR] 약속 - 내 약속 - 상세페이지 리팩토링
  CoNet/Main/Meeting/MeetingInfoEditViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/InfoVC/DecidedPlanInfoViewController.swift
Labels: 🐱 아현, 🛠️ refactor

#44 [PR] 마이페이지 > 회원 탈퇴 리팩토링
  CoNet/Main/MyPage/UserInfo/CompleteSignOutViewController.swift
  CoNet/Main/MyPage/UserInfo/SignOutPopUpViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#53 [PR] 모임 메인 > 모임 나가기, 삭제 팝업 리팩토링
  CoNet/Main/Meeting/MeetingDelPopUpViewController.swift
  CoNet/Main/Meeting/MeetingOutPopUpViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#57 [PR] horizontalEdges에서 offset으로 사용하던 내용을 inset으로 변경
  CoNet/Main/Meeting/MeetingDelPopUpViewController.swift
  CoNet/Main/Meeting/MeetingOutPopUpViewController.swift
  CoNet/Main/MyPage/InquireViewController.swift
  CoNet/Main/MyPage/LogoutPopUpViewController.swift
  CoNet/Main/MyPage/MyPageViewController.swift
  CoNet/Main/MyPage/UserInfo/ChangeNameViewController.swift
  CoNet/Main/MyPage/UserInfo/UserInfoViewController.swift
Labels: 🐥 안진, 🐛 bug, 🛠️ refactor

#39 [PR] 모임-메인 화면 리팩토링
  CoNet/Main/Meeting/MeetingMain/MeetingMainViewController.swift
Labels: 🐶 가은, 🛠️ refactor

#48 [PR] 메인 모임 - 모임 추가 버그 수정
  CoNet/Main/Meeting/MeetingTable/MeetingAddViewController.swift
Labels: 🐱 아현, 🐛 bug

#59 [PR] 약속 - 약속 만들기 리팩토링
  CoNet/Main/Meeting/Plan/MakePlanViewController.swift
Labels: 🐱 아현, 🛠️ refactor

#55 [PR] 초대코드 팝업 구현, 초대코드 공유 페이지에 적용
  CoNet.xcodeproj/project.pbxproj
  CoNet/Main/Components/PopUp/InviteCodePopUp.swift
  CoNet/Main/Meeting/InvitationCodeViewController.swift
Labels: 🐥 안진, ✨ feat, 🛠️ refactor

#62 [PR] 로그인 화면 리팩토링(인데 카카오톡 앱 로그인 오류 수정도 있음)
  CoNet.xcodeproj/project.pbxproj
  CoNet/API/HomeAPI.swift
  CoNet/API/MeetingMainAPI.swift
  CoNet/API/PlanTimeAPI.swift
  CoNet/Main/Auth/Login/AppleLoginButton.swift
  CoNet/Main/Auth/Login/KakaoLoginButton.swift
  CoNet/Main/Auth/Login/LoginViewController.swift
  CoNet/SceneDelegate.swift
Labels: 🐥 안진, 🐛 bug, 🛠️ refactor

#64 [PR] 이용약관 페이지 리팩토링
  CoNet.xcodeproj/project.pbxproj
  CoNet/Assets.xcassets/icon/SignUp/Contents.json
  CoNet/Assets.xcassets/icon/SignUp/checkbox 1.imageset/Contents.json
  CoNet/Assets.xcassets/icon/SignUp/checkbox 1.imageset/checkbox.png
  CoNet/Assets.xcassets/icon/SignUp/checkbox 1.imageset/checkbox3.png
  CoNet/Assets.xcassets/icon/SignUp/checkbox 2.imageset/Contents.json
  CoNet/Assets.xcassets/icon/SignUp/checkbox 2.imageset/checkbox.png
  CoNet/Assets.xcassets/icon/SignUp/checkbox 2.imageset/checkbox3.png
  CoNet/Assets.xcassets/icon/checkbox 1.imageset/checkbox 1.png
  CoNet/Assets.xcassets/icon/checkbox 2.imageset/checkbox 2.png
  CoNet/Main/Auth/SignUp/TermRow.swift
  CoNet/Main/Auth/SignUp/TermsOfUseViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#60 [PR] 약속 - 상세페이지 수정 리팩토링(네비게이션바 아직 해결못함, 나머지는 완료!!)
  CoNet/Main/Meeting/PlanList/PlanDetail/PlanDateButtonSheetViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/PlanEditDelBottomSheetViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/PlanInfoEditViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/Sheet/PlanMemberBottonSheetViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/Sheet/PlanTimePickerViewController.swift
Labels: 🏥 help, 🐱 아현, 🛠️ refactor

#67 [PR] 약속만들기 포커스 버그 수정
  CoNet/Main/Meeting/Plan/MakePlanViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/PlanInfoEditViewController.swift
Labels: 🐱 아현, 🐛 bug

#65 [PR] 회원가입>이름입력 페이지 리팩토링
  CoNet/Main/Auth/SignUp/EnterNameViewController.swift
Labels: 🐥 안진, 🛠️ refactor

#66 [PR] 린트 몇 개를 수정했어요!
  CoNet/API/PlanAPI.swift
  CoNet/Main/Meeting/MeetingTable/MeetingCodeViewController.swift
  CoNet/Main/Meeting/Plan/TimeInputViewController.swift
  CoNet/Main/Meeting/PlanList/PlanDetail/PlanInfoEditViewController.swift
Labels: 🐥 안진
